<?php


/*
 * Implementation of hook_menu
 */
function diy_filesystem_api_menu() {

  $items = array();
  $items['templates-list'] = array(
     'title' => 'DIY File System API',
     'description' => 'DIY File System API',
     'page callback' => 'diy_filesystem_api',
     'access callback' => 'diy_auth_user_access',
     'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/*
 * Form access Function
 */
function diy_auth_user_access($account=NULL) {
	if(user_is_anonymous()){
	  //return false;
	}
 return TRUE;
}

/*
 * DIY File System API Function
 */
function diy_filesystem_api() {
  $myJSON = '';
  try {
	  if(isset($_REQUEST['tid'])) {
		$tid = check_plain($_REQUEST['tid']);
		$node = node_load($tid);
		if(isset($node->field_template_location[LANGUAGE_NONE][0]['value'])) {
		  global $user;
		  if($user->uid) {
            $users['field_my_websites'][LANGUAGE_NONE][0]['target_id'] = $tid;
			user_save($user, $users);
		  }
		  global $base_url;
		  if(isset($_REQUEST['action'])) {
			$action = check_plain($_REQUEST['action']);
            drupal_goto($base_url.'/'.$node->field_template_location[LANGUAGE_NONE][0]['value']);       
		  }
		  drupal_goto($base_url.'/'.$node->field_template_location[LANGUAGE_NONE][0]['value']);//.'?mod=edit'
		}
		else { drupal_goto(''); }
	  }
	  else { drupal_goto(''); }
  }
  catch(Exception $e) {
	drupal_goto('');  
  }
}
function diy_file_external_file_save($directory) {
  if($directory) {

        $file = (object) array(
			'filename' => basename($directory),
			'filepath' => $directory,
			'filemime' => file_get_mimetype($directory),
			'filesize' => filesize($directory),
			'uid' => 1,
			'status' => 1,
			'timestamp' => time(),
			'uri' => $directory,
		);
		 drupal_write_record('file_managed', $file);       	
  }
  return $file;
}
function diy_file_external_save($path = NULL) {
  if($path) {
      $basename = basename($path);
	  $random = rand();
	  $directory = 'public://1_'.$random.$basename;
	  $files = file_get_contents($path);
	  $putcontent = file_put_contents($directory,$files);
		$file = (object) array(
			'filename' => basename($directory),
			'filepath' => $directory,
			'filemime' => file_get_mimetype($directory),
			'filesize' => filesize($directory),
			'uid' => 1,
			'status' => 1,
			'timestamp' => time(),
			'uri' => $directory,
		);
		 drupal_write_record('file_managed', $file);
	  }
	  return $file;
}

function videoembed($video  = NULL) {
  $videos = 'http://simpleinformation.com/themes/si_theme/video/video-bg.mp4';
  if($video) {
    $videos = check_plain($video);
  }
  print ' <video autoplay="" loop="" preload="auto" width="100%" height="100%">
               <source src="'.$videos.'" type="video/mp4">
               <source src="http://simpleinformation.com/themes/si_theme/video/video-bg.ogg" type="video/ogg">
               Your browser does not support the video tag.
            </video>';
			
}



function google_pie($pie =NULL) {
	print '<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
		<script type="text/javascript">
		  google.charts.load("current", {"packages":["corechart"]});
		  google.charts.setOnLoadCallback(drawChart);

		  function drawChart() {

			var data = google.visualization.arrayToDataTable([
			  ["Task", "Hours per Day"],
			  ["Work",     11],
			  ["Eat",      2],
			  ["Commute",  2]
			]);

			var options = {
			  title: "My Daily Activities"
			};

			var chart = new google.visualization.PieChart(document.getElementById("piechart"));

			chart.draw(data, options);
		  }
		</script>';
	
} 